workflows:
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: linux_x2

        triggering:
            events:                      
                - push

        cache:
            cache_paths:
                - ~/.gradle/caches

        environment:
            flutter: stable
            groups:
                - google_credentials_f
            android_signing:
                - codemagic
            vars:
                PACKAGE_NAME: "com.exam.codemagic_hello_world_android"

        scripts:
            - name: Set up local.properties
              script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
            - name: Get Flutter packages
              script: | 
                flutter pub get
            - name: Build AAB with Flutter
              script: | 
                flutter build appbundle --release
        artifacts:
            - build/**/outputs/**/*.aab
            - build/**/outputs/**/mapping.txt
            - flutter_drive.log

        publishing:
            google_play:
                credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
                track: internal
                submit_as_draft: true
            slack:
                channel: '#codemagic-hello-world-stack'
                notify_on_build_start: false
                notify:
                    success: false
                    failure: false



